version: '2'
services:
    wordpress:
      image: wordpress
      restart: always
      links:
        - db:mysql
      environment:
        WORDPRESS_DB_HOST: db:3306
        WORDPRESS_DB_PASSWORD: spiderpig
    db:
      image: mariadb
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: spiderpig