version: '2'
services:
    apache-proxy:
      image: mannionjames/docker-digital-ocean-apache
      ports:
        - "80:80"

    wordpress:
      image: mannionjames/docker-wordpress
      restart: always
      links:
        - db:mysql
      environment:
        WORDPRESS_DB_HOST: db:3306
        WORDPRESS_DB_NAME: myLovelyDatabase
        WORDPRESS_DB_USER: myLovelyUser
        WORDPRESS_DB_PASSWORD: myLovelyPasswprd
    db:
      image: mariadb:latest
      restart: always
      volumes_from:
        - db-data
      environment:
        MYSQL_DATABASE: myLovelyDatabase
        MYSQL_USER: myLovelyUser
        MYSQL_PASSWORD: myLovelyPasswprd
        MYSQL_ROOT_PASSWORD: myLovelyRootPasswprd
    db-data:
      image: mannionjames/mannionjames-maria-data:latest